### ISSUE TITLE
MT evaluation tool

### ISSUE THREAD

**Issue by kaldan007** [OpenPecha/MT-evaluation-tool#1]
**Description**:
We have done an experiment with our LLM on translation. Earlier we have fine tuned our LLM with zero shot translation, but this time we have fine tuned our LLM with Translation using Chain of thought.  In order to evaluate the experiment outcome, we need a tool in which we can rank our experiment output with ground truth translation, zero shot translation and COT translation. We will be giving a dataset which contains many data points. Each data points will contain source sentence, ground truth translation, zero short translation and COT translation.

**Inspiration**:
https://claude.site/artifacts/7b150eb8-7faa-4691-82c1-89125c29f707

Ranking needs to be save in db for further analysis. 

**Note**: We don't need reviewing mechanisms like other annotations

## Sub-tasks

- [x] Create a remix app 
    - [x] UI Design and Implementation 
       - [x] UI Features
           - [x] Implement a ranking interface for annotators to rank translation outputs (ground truth or target text, zero-shot, CoT)
           - [x] Add a sidebar to view the history of ranked evaluations by annotators
- [x] make the connection with db using Prisma
- [x] Define Prisma models for MT evaluation data and User
- [x] generate loader and pass initial annotator data from it to the UI
- [x] generate action to get data from inputs and update it on the database
- [x] admin
    - [x]  Add user list with a role-changing option
    - [x]  Implement a JSON file upload to seed translation data for ranking
- [x] Review
- [x] Deployment

extra note:
user should be able to log in by going to /?session={email}
eg.   http://localhost:8000/?session=tashi@gmail.com

## Card reviewer
- [x] @tentamdin

**Comment by Tech-lo** [comment]
@kaldan007 Just for clarification: the ranking will be based on Ground Truth Translation, Zero-Shot Translation, and COT Translation, and the source sentence data will be fetched from the database, correct? Regarding the Target Text, will that also be provided, or is there something else I need to consider? 
Also, about the buttons (Previous, Clear All, Next) in the sample, should these be implemented exactly as shown in the sample?

**Comment by kaldan007** [comment]
src text and ground truth or target will be in db. number of candidates will be not fixed. candates will be shipped as list.

**Comment by Tech-lo** [comment]
## Sub-tasks

- [ ] Create a remix app 
    - [ ] Initialize the Remix app
    - [ ] UI Design and Implementation
       - [ ] UI Features
           - [ ] Implement a ranking interface for annotators to rank translation outputs (ground truth or target text, zero-shot, CoT)
           - [ ] Add a sidebar to view the history of ranked evaluations by annotators
- [ ] make the connection with db using Prisma
- [ ] Define Prisma models for MT evaluation data and User
- [ ] generate loader and pass initial annotator data from it to the UI
- [ ] generate action to get data from inputs and update it on the database
- [ ] admin
    - [ ]  Add user list with a role-changing option
    - [ ]  Implement a JSON file upload to seed translation data for ranking


extra note:
user should be able to log in by going to /?session={email}
eg.   http://localhost:8000/?session=tashi@gmail.com

## Card reviewer
- [ ] @tentamdin

**Comment by Tech-lo** [comment]
## JSON format 
- [testing.json](https://github.com/user-attachments/files/18328433/testing.json)
Tested with this format

**Comment by Tech-lo** [comment]
@kaldan007  

Is this the format you would prefer?
- Proposed Format(By @tentamdin ):
    In the database, candidates are displayed as: ["Question", "Inquire", "Query"]
    After rankings are updated, the rankings appear as: ["Inquire", "Query", "Question"]
- Current Setup:
    In the database, candidates are displayed as: ["Question", "Inquire", "Query"]
    After rankings are updated, the rankings appear as: {"candidate1": 3, "candidate2": 1, "candidate3": 2}
    Let me know if you'd like the database to follow the proposed format later on or if the current setup works for now.

**Comment by Tech-lo** [comment]
@kaldan007 
update: i have assigned you admin role in the tool with ur email. You can test the functionality on the deployed link.
